package cauãlindo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SESI_SENAI
 */
public class NewJFrame extends javax.swing.JFrame {
    ArrayList<Aluno> cauãlindo = new ArrayList<>();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        cauãvancoco = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        camponome = new javax.swing.JTextField();
        campocpf = new javax.swing.JTextField();
        campoidade = new javax.swing.JTextField();
        campomatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radioF = new javax.swing.JRadioButton();
        radioM = new javax.swing.JRadioButton();
        radioC = new javax.swing.JRadioButton();
        jButtonok = new javax.swing.JButton();
        jButtoncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Nome");

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Cpf");

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("Idade");

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Matricula");

        camponome.setText("jTextField2");

        campocpf.setText("jTextField3");

        campoidade.setText("jTextField4");

        campomatricula.setText("jTextField5");
        campomatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campomatriculaActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Sexo");

        cauãvancoco.add(radioF);
        radioF.setText("Feminino");

        cauãvancoco.add(radioM);
        radioM.setText("Masculino");

        cauãvancoco.add(radioC);
        radioC.setText("Cauã");

        jButtonok.setForeground(new java.awt.Color(51, 204, 0));
        jButtonok.setText("ok");
        jButtonok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonokActionPerformed(evt);
            }
        });

        jButtoncancelar.setForeground(new java.awt.Color(255, 0, 0));
        jButtoncancelar.setText("cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                    .addComponent(campomatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(campocpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(camponome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(59, 59, 59)
                                .addComponent(campoidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118))))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radioF)
                        .addGap(10, 10, 10)
                        .addComponent(radioM))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtoncancelar)
                        .addGap(53, 53, 53)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonok)
                    .addComponent(radioC))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(camponome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campocpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campomatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel6)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioF)
                    .addComponent(radioM)
                    .addComponent(radioC))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoncancelar)
                    .addComponent(jButtonok))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>                        

    private void campomatriculaActionPerformed(java.awt.event.ActionEvent evt) {                                               
      String nome = camponome.getText ();
      int idade = Integer.parseInt(campoidade.getText());
      String matricula = campomatricula.getText ();
      //String fotoscauã = campofotoscauã.getText ();
      String cpf = campocpf.getText ();
      char sexo = ' ';
        if (radioM.isSelected()){
            sexo = 'm';
        }
      else  if (radioF.isSelected()){
            sexo = 'F';
        }
      else if(radioC.isSelected()){
          sexo = 'c';
      }
        
        Aluno a = new Aluno(matricula);
        //a.SetFotoscauã(fotoscauã);
        a.setNome(nome);
        a.setCpf(cpf);
        a.setIdade(idade);
        a.setSexo(sexo);
        cauãlindo.add(a);
        
        //campoFotoscauã.setText(null);
        camponome.setText(null);
        campocpf.setText(null);
        campomatricula.setText(null);
        campoidade.setText(null);
        cauãvancoco.clearSelection();
        JOptionPane.showMessageDialog(null, "Aluno cadastrado com sucesso!");
    
    }                                              

    private void jButtonokActionPerformed(java.awt.event.ActionEvent evt) {                                          

        String mensagem = "Alunos\n";
        for(Aluno a: cauãlindo) {
            mensagem += "nome: "+a.getNome()+"\n";
            mensagem += "cpf: "+a.getCpf()+"\n";
            mensagem += "matricula: "+a.getMatricula()+"\n";
            mensagem += "idade: "+a.getIdade()+"\n";
            mensagem += "sexo: "+a.getSexo()+"\n";
            mensagem += "-------------------\n";
           
        }
        JOptionPane.showMessageDialog(null, mensagem);
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextField campocpf;
    private javax.swing.JTextField campoidade;
    private javax.swing.JTextField campomatricula;
    private javax.swing.JTextField camponome;
    private javax.swing.ButtonGroup cauãvancoco;
    private javax.swing.JButton jButtoncancelar;
    private javax.swing.JButton jButtonok;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton radioC;
    private javax.swing.JRadioButton radioF;
    private javax.swing.JRadioButton radioM;
    // End of variables declaration                   
}
