package cauãlindo;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SESI_SENAI
 */
public class NewJFrame extends javax.swing.JFrame {
    ArrayList<Aluno> cauãlindo = new ArrayList<>();
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        cauãvancoco = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        camponome = new javax.swing.JTextField();
        campocpf = new javax.swing.JTextField();
        campoidade = new javax.swing.JTextField();
        campomatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radioF = new javax.swing.JRadioButton();
        radioM = new javax.swing.JRadioButton();
        radioC = new javax.swing.JRadioButton();
        jButtonok = new javax.swing.JButton();
        jButtoncancelar = new javax.swing.JButton();
